name: Build GridFlow CLI and GUI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
        python-version: [ "3.10" ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgeos-dev libproj-dev libnetcdf-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable
      run: |
        pyinstaller --onefile gridflow.spec
      env:
        PYTHONPATH: .

    - name: Rename executable
      shell: bash
      run: |
        case "${{ matrix.os }}" in
          windows-latest)
            mv dist/gridflow.exe dist/gridflow-windows.exe
            ;;
          macos-latest)
            mv dist/gridflow dist/gridflow-macos
            ;;
          ubuntu-latest)
            mv dist/gridflow dist/gridflow-linux
            ;;
        esac

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gridflow-executables-${{ matrix.os }}
        path: |
          dist/gridflow-*

    - name: Attach to release
      if: github.event_name == 'release' && github.event.action == 'published'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/gridflow-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}