name: Build GridFlow CLI and GUI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
        python-version: [ "3.10" ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgeos-dev libproj-dev libnetcdf-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build CLI executable
      run: |
        pyinstaller gridflow-cli.spec
      env:
        PYTHONPATH: .

    - name: Build GUI executable
      run: |
        pyinstaller GridFlowGUI.spec
      env:
        PYTHONPATH: .

    - name: Rename executables
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          mv dist/gridflow-cli/gridflow-cli.exe dist/gridflow-cli-windows.exe
          mv dist/GridFlowGUI/GridFlowGUI.exe dist/gridflow-gui-windows.exe
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          mv dist/gridflow-cli/gridflow-cli dist/gridflow-cli-macos
          mv dist/GridFlowGUI/GridFlowGUI dist/gridflow-gui-macos
        else
          mv dist/gridflow-cli/gridflow-cli dist/gridflow-cli-linux
          mv dist/GridFlowGUI/GridFlowGUI dist/gridflow-gui-linux
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gridflow-executables-${{ matrix.os }}
        path: |
          dist/gridflow-cli-*
          dist/gridflow-gui-*

    - name: Upload to release
      if: github.event_name == 'release' && github.event.action == 'published'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/gridflow-cli-*
          dist/gridflow-gui-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}